### ISSUE TITLE
Storage Image filename issue.

### ISSUE THREAD

**Issue by pctn0007** [pctn0007/Motus#3]
When images are added to the Storage database, the file names save as follow: 11Apr2019_19:26:16.jpg  

This needs to change to: 11Apr2019_19_26_16.jpg in order to prevent request errors.

**Comment by BlueDaroosh** [comment]
I'm on it chief. You're paying me for overtime by the way.

**Comment by BlueDaroosh** [comment]
Fixed request error string encoding in image names from ":" to "_". Also adjusted code to save images into detection's directory of image storage. Test for proof of fix. If confirmed, close this thread.

**Comment by pctn0007** [comment]
Not quite fixed yet. In the Real-time database section under Detection JSON objects, the "Picture" key value includes "Detections/" in the value. It should just be the filename and extension, not full directory and extension.

**Comment by BlueDaroosh** [comment]
oof, lemme fix that

**Comment by BlueDaroosh** [comment]
Fixed. Closing thread.
